/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nsselection

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/JieranAgileCore/nssf/internal/logger"
	"github.com/JieranAgileCore/nssf/internal/sbi/producer"
	"github.com/JieranAgileCore/openapi"
	"github.com/JieranAgileCore/openapi/models"
	"github.com/JieranAgileCore/util/httpwrapper"
)

func HTTPNetworkSliceInformationDocument(c *gin.Context) {
	req := httpwrapper.NewRequest(c.Request, nil)

	rsp := producer.HandleNSSelectionGet(req)

	responseBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.NsselLog.Errorln(err)
		problemDetails := models.ProblemDetails{
			Status: http.StatusInternalServerError,
			Cause:  "SYSTEM_FAILURE",
			Detail: err.Error(),
		}
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody)
	}
}
