/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/JieranAgileCore/openapi"
	"github.com/JieranAgileCore/openapi/models"
	"github.com/JieranAgileCore/udr/internal/logger"
	"github.com/JieranAgileCore/udr/internal/sbi/producer"
	"github.com/JieranAgileCore/util/httpwrapper"
)

// HTTPGetSharedData - retrieve shared data
func HTTPGetSharedData(c *gin.Context) {
	sharedDataIdArray := c.QueryArray("shared-data-ids")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Query["sharedDataIds"] = sharedDataIdArray

	rsp := producer.HandleGetSharedData(req)

	responseBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := models.ProblemDetails{
			Status: http.StatusInternalServerError,
			Cause:  "SYSTEM_FAILURE",
			Detail: err.Error(),
		}
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody)
	}
}
